version: '3.8'

services:
  faketorrent:
    restart: unless-stopped
    container_name: faketorrent
    build: .
    hostname: faketorrent
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.faketorrent-http.entrypoints: web
      traefik.http.routers.faketorrent-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.faketorrent-http.rule: Host(`faketorrent.davyjones.media`)
      traefik.http.routers.faketorrent-http.service: faketorrent
      traefik.http.routers.faketorrent.entrypoints: websecure
      traefik.http.routers.faketorrent.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.faketorrent.rule: Host(`faketorrent.davyjones.media`)
      traefik.http.routers.faketorrent.service: faketorrent
      traefik.http.routers.faketorrent.tls.certresolver: cfdns
      traefik.http.routers.faketorrent.tls.options: securetls@file
      traefik.http.services.faketorrent.loadbalancer.server.port: 8000
    volumes:
      - ./logs:/app/logs

networks:
  saltbox:
    external: true
